language: scala
os: linux
jdk:
  - oraclejdk8
install: if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; sudo apt-get install -qq bc tesseract-ocr gocr ocrad imagemagick; fi
script: ./runbot -c
