language: scala
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq bc
  - sudo apt-get install -qq tesseract-ocr gocr ocrad
script:
  - ./runbot -c
